# Generated by Django 3.1.2 on 2020-10-31 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitefazentech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecieDeVaca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeProducao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Varegista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=100)),
                ('tipo_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefazentech.tipoestabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoDeLeite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inseminacao', models.BooleanField(default=False)),
                ('ultima_ordenha', models.DateField()),
                ('temperatura_armazenamento', models.IntegerField()),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefazentech.especiedevaca')),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('valor', models.FloatField()),
                ('peso', models.FloatField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefazentech.tipodeproducao')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=0)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefazentech.tipoequipamento')),
            ],
        ),
        migrations.CreateModel(
            name='ControleDeAnimalEPlantio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_chegada', models.DateField()),
                ('data_ultima_producao', models.DateField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefazentech.tipodeproducao')),
            ],
        ),
    ]
