# Generated by Django 3.1.2 on 2020-11-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitefazentech', '0002_controledeanimaleplantio_equipamento_especiedevaca_producao_producaodeleite_tipodeproducao_tipoequip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varegista',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
