# Generated by Django 3.1.2 on 2020-11-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitefazentech', '0003_auto_20201101_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleDeAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_chegada', models.DateField()),
                ('data_ultima_producao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ControleDePlantio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_chegada', models.DateField()),
                ('data_ultima_producao', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='ControleDeAnimalEPlantio',
        ),
        migrations.AddField(
            model_name='producaodeleite',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitefazentech.controledeanimal'),
        ),
    ]
